---
- name: "Display AWS EC2 facts"
  gather_facts: no
  hosts: localhost
  tasks:

    - ec2_instance_facts:
        region: "ca-central-1"
      register: ec2_facts

    - debug:
        var: ec2_facts
  