---
- name: "Get Facts from network devices"
  gather_facts: no
  hosts: all
  tasks:
    - when: ansible_network_os == "ios"
      ios_facts:
        register: facts

    - debug:
        var: facts
