---
- name: Check routes
  loop: "{{ request.l3vpn | dict2items }}"
  cisco.ios.ios_command:
    commands: "show ip route vrf {{ request.vpn_name }}"
    retries: 1
    wait_for:
    - result[0] contains '{{ item.value.prefix }}'
  register: show_route_output
  ignore_errors: yes
  
- debug:
    var: show_route_output