---
- name: "Configurer L3VPN from request"
  gather_facts: no
  hosts: core_ipvpn
  tasks:

  - when: inventory_hostname in request.l3vpn
    debug:
      msg: "{{ topo[inventory_hostname].interfaces }}"

  - name: "Looking for Client interface on PE"
    when: inventory_hostname in request.l3vpn
    set_fact:
      client_interface: "{{ (topo[ inventory_hostname ].interfaces | selectattr('role', 'equalto', 'client') | list)[0] }}"

  - debug:
      var: client_interface
  
  - name: "Configure PE client interfaces"
    when: inventory_hostname in request.l3vpn
    cisco.ios.ios_interfaces:
      config:
      - name: "{{ client_interface.name  }}"
        description: "{{ request.vpn_name }} - Ref:{{ request.ticket_no }}"
