---
- name: "Initial setup"
  gather_facts: no
  hosts: core_ipvpn
  tasks: 

  - ios_facts:
    register: test
    
  - include_role:
      name: ospf

  - include_role:
      name: loopbacks

  - include_role:
      name: lldp

  - include_role:
      name: bgp

  - cisco.ios.ios_config:
      save_when: always