---
- name: "Create a new VLAN in Datacenter"
  hosts: all
  gather_facts: no
  tasks:

  - name: "Create VLAN in ESXi"
    community.vmware.vmware_portgroup:
      hosts: "ns545929"
      # hostname: "{{ esxi_hostname }}"
      # username: "{{ esxi_username }}"
      # password: "{{ esxi_password }}"
      switch: "internal"
      portgroup: "vlan{{ vlan_id }}"
      vlan_id: "{{ vlan_id }}"
      validate_certs: no
    delegate_to: localhost
    run_once: True

  - name: "Create sub-interfaces on routers"
    cisco.ios.ios_interfaces:
      config:
      - name: "GigabitEthernet3.{{ vlan_id }}"
        description: "VMWare interface vlan {{ vlan_id }}"
        enabled: true

    