---
- name: Template request summary web page
  template:
    dest: "{{ request.ticket_no }}.html"
    src: "config.html.j2"
  check_mode: no

- name: Upload request summary web page to S3
  amazon.aws.aws_s3:
    bucket: mouimet-l3vpn-config
    object: "{{ request.ticket_no }}.html"
    src: "{{ request.ticket_no }}.html"
    mode: put
    permission:
      - public-read
  check_mode: no
  register: s3_upload

- debug:
    msg:
      - "Vous pouvez consulter le rapport du changement a l'URL suivant:"
      - "{{ s3_upload.url.split('?')[0] }}"
