---
- name: "Configure Loopback interfaces"
  cisco.ios.ios_interfaces:
    config:
    - name: Loopback0
      enabled: true
    state: merged

- name: "Configure Loopback interfaces"
  when: inventory_hostname == "r1"
  cisco.ios.ios_l3_interfaces:
    config:
    - name: Loopback0
      ipv4:
      - address: 10.255.255.1/32
    state: merged

- name: "Configure Loopback interfaces"
  when: inventory_hostname == "r2"
  cisco.ios.ios_l3_interfaces:
    config:
    - name: Loopback0
      ipv4:
      - address: 10.255.255.2/32
    state: merged

- name: "Configure Loopback interfaces"
  when: inventory_hostname == "r3"
  cisco.ios.ios_l3_interfaces:
    config:
    - name: Loopback0
      ipv4:
      - address: 10.255.255.3/32
    state: merged

- name: "Configure Loopback interfaces"
  when: inventory_hostname == "r4"
  cisco.ios.ios_l3_interfaces:
    config:
    - name: Loopback0
      ipv4:
      - address: 10.255.255.4/32
    state: merged