---

- set_fact:
    command_list: []

- name: "Looking for Client interface on PE"
  set_fact:
    client_interface: "{{ (topo[ inventory_hostname ].interfaces | selectattr('role', 'equalto', 'client') | list)[0] }}"

- name: "Looking for Client interface on PE"
  set_fact:
    client_interface_fullname: "{{ client_interface.name  }}.{{ request.l3vpn[inventory_hostname].vlan }}"

- debug:
    msg: 
    - "{{ client_interface }}"
    - "{{ client_interface_fullname }}"

- name: "Configure new VRF {{ request.vpn_name }}"
  cisco.ios.ios_vrf:
    name: "{{ request.vpn_name }}"
    state: absent
  register: vrf_output

- name: "Configure PE client L3 interfaces"
  cisco.ios.ios_interfaces:
    config:
    - name: "{{ client_interface_fullname }}"
    state: gathered
  register: intf_output

- when: intf_output.gathered | selectattr('name', 'equalto', client_interface_fullname) | list | count == 1
  cisco.ios.ios_config:
    lines:
    - "no interface {{ (intf_output.gathered | selectattr('name', 'equalto', client_interface_fullname) | list)[0].name }} "
  register: remove_intf_output


- when: vrf_output.changed
  set_fact:
    command_list: "{{ command_list + vrf_output.commands }}"

- when: remove_intf_output is defined and remove_intf_output.changed 
  set_fact:
    command_list: "{{ command_list + remove_intf_output.commands }}"

- debug:
    msg: "{{ command_list }}"
