---
- name: Send slack message
  hosts: localhost
  gather_facts: no

  tasks:

  - name: Send notification message via Slack
    community.general.slack:
      token: T01DW2WQ2NM/B01LEJL8P60/ZlCoRFrR6oL6Mk2njcDVyFMX
      msg: '{{ message }}'
    delegate_to: localhost